image: zephyrprojectrtos/zephyr-build

tasks:
  - init: |
      mkdir -p .west
      cat <<EOF > .west/config
      [manifest]
      path = modules/lib/golioth
      file = west.yml
      EOF
      west update -o=--depth=1 -n
      west patch --apply

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
    