name: 🐞 Bug Report
labels: ["bug"]
body:
  - type: input
    id: zephyr-version
    attributes:
      label: Which Zephyr version are you running?
    validations:
      required: true
  - type: input
    id: dsdk-version
    attributes:
      label: Golioth SDK Commit Hash
      description: To identify version of SDK you are using, please share its commit hash. If you're sure you are using the latest version, say "latest"
      value: latest
    validations:
      required: true
  - type: input
    id: hardware-target
    attributes:
      label: Hardware Target
      description: What hardware platform are you using? (e.g. nRF91, ESP32, QEMU, ...)
    validations:
      required: false
  - type: dropdown
    id: host-os
    attributes:
      label: What host OS are you using?
      options:
        - Windows
        - Mac
        - Ubuntu
        - Other (Mention Below)
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs, console output, or any kind of debug information
      description: Please copy and paste any relevant debug information. This will be automatically formatted into code, so no need for backticks.
      render: shell
