blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.com/invite/qKjmvzMVYR
    about: Chat with the community and our team on Discord. Office hours at 10:00am PST every Wednesday!
