name: 🚀 Feature request
description: Suggest new features or enhancements to existing features
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Describe the feature you would like
      description: A concise description of the functionality you would like to have
    validations:
      required: true
  - type: input
    id: feature-reference
    attributes:
      label: Does it relate to existing feature? If so, please provide its name.
    validations:
      required: false
