/*
 * Copyright (c) 2022 Golioth, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <errno.h>
#include <qcbor/posix_error_map.h>

int qcbor_error_to_posix(QCBORError qerr)
{
	switch (qerr) {
	case QCBOR_SUCCESS:
		return 0;
	case QCBOR_ERR_BUFFER_TOO_SMALL:
		return -ENOSPC;
	case QCBOR_ERR_ENCODE_UNSUPPORTED:
		return -EINVAL;
	case QCBOR_ERR_BUFFER_TOO_LARGE:
		return -E2BIG;
	case QCBOR_ERR_ARRAY_NESTING_TOO_DEEP:
		return -E2BIG;
	case QCBOR_ERR_CLOSE_MISMATCH:
		return -EINVAL;
	case QCBOR_ERR_ARRAY_TOO_LONG:
		return -E2BIG;
	case QCBOR_ERR_TOO_MANY_CLOSES:
		return -EINVAL;
	case QCBOR_ERR_ARRAY_OR_MAP_STILL_OPEN:
		return -EBUSY;
	case QCBOR_ERR_BAD_TYPE_7:
	case QCBOR_ERR_EXTRA_BYTES:
		return -EBADMSG;
	case QCBOR_ERR_UNSUPPORTED:
		return -ENOTSUP;
	case QCBOR_ERR_ARRAY_OR_MAP_UNCONSUMED:
		return -EBADMSG;
	case QCBOR_ERR_BAD_INT:
	case QCBOR_ERR_INDEFINITE_STRING_CHUNK:
	case QCBOR_ERR_HIT_END:
	case QCBOR_ERR_BAD_BREAK:
		return -EBADMSG;
	case QCBOR_ERR_INPUT_TOO_LARGE:
	case QCBOR_ERR_ARRAY_DECODE_NESTING_TOO_DEEP:
	case QCBOR_ERR_ARRAY_DECODE_TOO_LONG:
		return -E2BIG;
	case QCBOR_ERR_STRING_TOO_LONG:
	case QCBOR_ERR_BAD_EXP_AND_MANTISSA:
		return -EBADMSG;
	case QCBOR_ERR_NO_STRING_ALLOCATOR:
	case QCBOR_ERR_STRING_ALLOCATE:
		return -ENOMEM;
	case QCBOR_ERR_TOO_MANY_TAGS:
		return -E2BIG;
	case QCBOR_ERR_MAP_LABEL_TYPE:
		return -EBADMSG;
	case QCBOR_ERR_UNEXPECTED_TYPE:
		return -ENOMSG;
	case QCBOR_ERR_BAD_TAG_CONTENT:
		return -EBADMSG;
	case QCBOR_ERR_DUPLICATE_LABEL:
		return -ELOOP;
	case QCBOR_ERR_MEM_POOL_SIZE:
		return -ENOBUFS;
	case QCBOR_ERR_INT_OVERFLOW:
	case QCBOR_ERR_DATE_OVERFLOW:
		return -EOVERFLOW;
	case QCBOR_ERR_EXIT_MISMATCH:
		return -EINVAL;
	case QCBOR_ERR_NO_MORE_ITEMS:
		return -EAGAIN;
	case QCBOR_ERR_LABEL_NOT_FOUND:
		return -EACCES;
	case QCBOR_ERR_NUMBER_SIGN_CONVERSION:
		return -EINVAL;
	case QCBOR_ERR_CONVERSION_UNDER_OVER_FLOW:
		return -EOVERFLOW;
	case QCBOR_ERR_MAP_NOT_ENTERED:
		return -ESPIPE;
	case QCBOR_ERR_CALLBACK_FAIL:
		return -EINTR;
	case QCBOR_ERR_FLOAT_DATE_DISABLED:
	case QCBOR_ERR_HALF_PRECISION_DISABLED:
	case QCBOR_ERR_HW_FLOAT_DISABLED:
		return -ENOSYS;
	case QCBOR_ERR_FLOAT_EXCEPTION:
		return -EINVAL;
	case QCBOR_ERR_INDEF_LEN_STRINGS_DISABLED:
	case QCBOR_ERR_INDEF_LEN_ARRAYS_DISABLED:
		return -ENOSYS;
	case QCBOR_ERR_CANNOT_CANCEL:
		return -ECANCELED;
	case QCBOR_ERR_ALL_FLOAT_DISABLED:
		return -ENOSYS;
	}

	return -ENOTSUP;
}
