name: Deploy Doxygen to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt install doxygen graphviz
      - name: Generate Doxygen
        run: |
          cd docs/doxygen
          doxygen
      - name: Deploy docs to dev
        # The 'if' will prevent running this step if in a fork pull request
        if: ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLIOTH }}'
          projectId: golioth
          target: docs-dev
          entryPoint: docs
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
